### PR TITLE
Fixed reference to AWSURLRequestRetryHandler

### LINKED ISSUE #460: 2.4.8 Not compiling with Xcode8GM
/redacted/Pods/AWSS3/AWSS3/AWSS3RequestRetryHandler.h:16:9: 'AWSURLRequestRetryHandler.h' file not found

Using the following 
```
 pod 'AWSCore'
    pod 'AWSS3'
    pod 'AWSCognito'
    pod 'AWSMobileAnalytics'
```

### PR DESCRIPTION
**Pull request by arvindravi**
This includes a fix to a small referencing issue in `v2.4.8`. Fixes #460.

### CODE REVIEW

**Comment by karthiksaligrama** [comment]
Thanks for the PR. will merge this in next release

File: AWSS3/AWSS3RequestRetryHandler.h [hunk 1]
```diff
@@ -13,8 +13,8 @@
 // permissions and limitations under the License.
 //
 
-#import "AWSURLRequestRetryHandler.h"
+#import "AWSCore/AWSURLRequestRetryHandler.h"
```
Comment (karthiksaligrama) [inline AWSS3/AWSS3RequestRetryHandler.h]: can you change this to `#import <AWSCore/AWSURLRequestRetryHandler.h>`

Comment (arvindravi) [inline AWSS3/AWSS3RequestRetryHandler.h]: Done!
